apiVersion: v1
kind: Service
metadata:
  name: nullclaw-web
  namespace: nullclaw
  labels:
    name: nullclaw
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nullclaw
  ports:
    - name: gateway
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: web
      port: 32123
      targetPort: 32123
      protocol: TCP
